@host = http://127.0.0.1:48101

### ClientA 健康检查
GET {{host}}/actuator/health

### ClientA Ping
GET {{host}}/api/v1/client-a/demo/ping

### ClientA 通过 UCA-Base 发现并调用 ClientB
GET {{host}}/api/v1/client-a/demo/call-b
